import { Injectable } from '@angular/core';
import { ClientPrimaveraOrdersResponse } from './clients.types';

@Injectable({
    providedIn: 'root',
})
export class ClientsMockService {
    constructor() {}

    public getMockClientOrders(
        clientCode: string,
        isOnlyPastMonth: boolean
    ): ClientPrimaveraOrdersResponse {
        const mockData: Record<string, ClientPrimaveraOrdersResponse> = {
            '010064': {
                result: 'success',
                result_code: 200,
                total: 2,
                primavera_orders: [
                    {
                        primavera_order_header: {
                            Id: 'ECL 1/23',
                            TipoDoc: 'ECL',
                            Serie: '2023',
                            NumDoc: 1,
                            TipoEntidade: 'C',
                            Entidade: 'CLI001',
                            Nome: 'Metalúrgica Portuguesa, Lda',
                            NumContribuiente: '507452361',
                            TotalDocumento: 2891.42,
                            Moeda: 'EUR',
                            Cambio: 1,
                            DataDoc: '2023-05-15',
                            Estado: 'Fechada',
                            DescEstado: 'Fechada',
                            MoradaAltEntrega: null,
                            Morada: 'Rua da Indústria, 123',
                            Morada2: null,
                            Localidade: 'Braga',
                            CodPostal: '4700',
                            CodPostalLocalidade: '4700-352 Braga',
                            Distrito: 'Braga',
                            Pais: 'PT',
                            DataCarga: null,
                            Matricula: null,
                            LocalCarga: 'Armazém',
                            MoradaCarga: 'Rua Principal 45',
                            Morada2Carga: null,
                            LocalidadeCarga: 'Braga',
                            CodPostalCarga: '4700',
                            CodPostalLocalidadeCarga: '4700-352 Braga',
                            DistritoCarga: null,
                            PaisCarga: 'PT',
                            DataDescarga: null,
                            LocalDescarga: 'Obra',
                            MoradaDescarga: 'Rua da Indústria, 123',
                            Morada2Descarga: null,
                            LocalidadeDescarga: null,
                            CodPostalDescarga: '4700',
                            CodPostalLocalidadeDescarga: '4700-352 Braga',
                            DistritoDescarga: null,
                            PaisDescarga: null,
                            EntidadeDescarga: 'CLI001',
                            TipoEntidadeDescarga: 'C',
                            ObservacoesCabec: null,
                            Referencia: 'Encomenda Maio',
                            DescontoEntidade: 0,
                            DescontoFinanceiro: 0,
                            ModoPagamento: 'Transferência',
                            CondicaoPagamento: '30 dias',
                            DataVencimento: '2023-06-15',
                            ModoExpedicao: null,
                            TipoEntidadeFaturacao: 'C',
                            EntidadeFaturacao: 'CLI001',
                            MoradaFaturacao: 'Rua da Indústria, 123',
                            Morada2Faturacao: null,
                            LocalidadeFaturacao: 'Braga',
                            CodPostalFaturacao: '4700',
                            LocalidadeCodPostalFaturacao: '4700-352 Braga',
                            DistritoFaturacao: 'Braga',
                            EspacoFiscal: 'PT',
                            RegimeIva: 'Normal',
                            TipoOperacaoCabec: null,
                            DescTipoOperacaoCabec: null,
                            Documento: 'ECL 1/23',
                            VendedorCabec: 'V001',
                            NomeVendedorCabec: 'Lucas Remígio',
                        },
                        primavera_order_line: [
                            {
                                IdCabec: 'ECL 1/23',
                                Id: '1',
                                TipoDoc: 'ECL',
                                Serie: '2023',
                                NumDoc: 1,
                                NumLinha: 1,
                                Artigo: 'FERRO001',
                                Descricao: 'Armações de Ferro 12mm',
                                PrecUnit: 75.5,
                                Quantidade: 15,
                                PrecoLiquido: 1132.5,
                                Moeda: 'EUR',
                                Unidade: 'KG',
                                CodIva: 'NOR',
                                TaxaIva: 23,
                                Armazem: 'A1',
                                Lote: '',
                                Desconto1: 0,
                                Desconto2: 0,
                                Desconto3: 0,
                                DataLinha: '2023-05-15',
                                DataEntrega: '2023-05-20',
                                Vendedor: 'V001',
                                NomeVendedor: 'Lucas Remígio',
                                ComissaoVendedor: 2,
                                Observacoes: null,
                                TipoOperacao: null,
                                DescTipoOpercao: null,
                                IvaRegraCalculo: 'Normal',
                                CodigoPautal: null,
                                MassaLiqLinha: 150,
                                ValorLiqLinha: 1132.5,
                                IdObra: null,
                            },
                            {
                                IdCabec: 'ECL 1/23',
                                Id: '2',
                                TipoDoc: 'ECL',
                                Serie: '2023',
                                NumDoc: 1,
                                NumLinha: 2,
                                Artigo: 'METAL005',
                                Descricao: 'Perfis Metálicos 30x40',
                                PrecUnit: 121.83,
                                Quantidade: 10,
                                PrecoLiquido: 1218.25,
                                Moeda: 'EUR',
                                Unidade: 'UN',
                                CodIva: 'NOR',
                                TaxaIva: 23,
                                Armazem: 'A1',
                                Lote: '',
                                Desconto1: 0,
                                Desconto2: 0,
                                Desconto3: 0,
                                DataLinha: '2023-05-15',
                                DataEntrega: '2023-05-20',
                                Vendedor: 'V001',
                                NomeVendedor: 'Lucas Remígio',
                                ComissaoVendedor: 2,
                                Observacoes: null,
                                TipoOperacao: null,
                                DescTipoOpercao: null,
                                IvaRegraCalculo: 'Normal',
                                CodigoPautal: null,
                                MassaLiqLinha: 250,
                                ValorLiqLinha: 1218.25,
                                IdObra: null,
                            },
                        ],
                    },
                    {
                        primavera_order_header: {
                            Id: 'ECL 8/23',
                            TipoDoc: 'ECL',
                            Serie: '2023',
                            NumDoc: 8,
                            TipoEntidade: 'C',
                            Entidade: 'CLI001',
                            Nome: 'Metalúrgica Portuguesa, Lda',
                            NumContribuiente: '507452361',
                            TotalDocumento: 2306.56,
                            Moeda: 'EUR',
                            Cambio: 1,
                            DataDoc: '2023-06-22',
                            Estado: 'Pendente',
                            DescEstado: 'Pendente',
                            MoradaAltEntrega: null,
                            Morada: 'Rua da Indústria, 123',
                            Morada2: null,
                            Localidade: 'Braga',
                            CodPostal: '4700',
                            CodPostalLocalidade: '4700-352 Braga',
                            Distrito: 'Braga',
                            Pais: 'PT',
                            DataCarga: null,
                            Matricula: null,
                            LocalCarga: 'Armazém',
                            MoradaCarga: 'Rua Principal 45',
                            Morada2Carga: null,
                            LocalidadeCarga: 'Braga',
                            CodPostalCarga: '4700',
                            CodPostalLocalidadeCarga: '4700-352 Braga',
                            DistritoCarga: null,
                            PaisCarga: 'PT',
                            DataDescarga: null,
                            LocalDescarga: 'Obra',
                            MoradaDescarga: 'Rua da Indústria, 123',
                            Morada2Descarga: null,
                            LocalidadeDescarga: null,
                            CodPostalDescarga: '4700',
                            CodPostalLocalidadeDescarga: '4700-352 Braga',
                            DistritoDescarga: null,
                            PaisDescarga: null,
                            EntidadeDescarga: 'CLI001',
                            TipoEntidadeDescarga: 'C',
                            ObservacoesCabec: null,
                            Referencia: 'Encomenda Junho',
                            DescontoEntidade: 0,
                            DescontoFinanceiro: 0,
                            ModoPagamento: 'Transferência',
                            CondicaoPagamento: '30 dias',
                            DataVencimento: '2023-07-22',
                            ModoExpedicao: null,
                            TipoEntidadeFaturacao: 'C',
                            EntidadeFaturacao: 'CLI001',
                            MoradaFaturacao: 'Rua da Indústria, 123',
                            Morada2Faturacao: null,
                            LocalidadeFaturacao: 'Braga',
                            CodPostalFaturacao: '4700',
                            LocalidadeCodPostalFaturacao: '4700-352 Braga',
                            DistritoFaturacao: 'Braga',
                            EspacoFiscal: 'PT',
                            RegimeIva: 'Normal',
                            TipoOperacaoCabec: null,
                            DescTipoOperacaoCabec: null,
                            Documento: 'ECL 8/23',
                            VendedorCabec: 'V001',
                            NomeVendedorCabec: 'Lucas Remígio',
                        },
                        primavera_order_line: [
                            {
                                IdCabec: 'ECL 8/23',
                                Id: '1',
                                TipoDoc: 'ECL',
                                Serie: '2023',
                                NumDoc: 8,
                                NumLinha: 1,
                                Artigo: 'FERRO003',
                                Descricao: 'Vigas de Ferro 20mm',
                                PrecUnit: 375.05,
                                Quantidade: 5,
                                PrecoLiquido: 1875.25,
                                Moeda: 'EUR',
                                Unidade: 'UN',
                                CodIva: 'NOR',
                                TaxaIva: 23,
                                Armazem: 'A1',
                                Lote: '',
                                Desconto1: 0,
                                Desconto2: 0,
                                Desconto3: 0,
                                DataLinha: '2023-06-22',
                                DataEntrega: '2023-06-30',
                                Vendedor: 'V001',
                                NomeVendedor: 'Lucas Remígio',
                                ComissaoVendedor: 2,
                                Observacoes: null,
                                TipoOperacao: null,
                                DescTipoOpercao: null,
                                IvaRegraCalculo: 'Normal',
                                CodigoPautal: null,
                                MassaLiqLinha: 500,
                                ValorLiqLinha: 1875.25,
                                IdObra: null,
                            },
                        ],
                    },
                ],
            },
        };

        // Default empty response
        const emptyResponse: ClientPrimaveraOrdersResponse = {
            result: 'success',
            result_code: 200,
            total: 0,
            primavera_orders: [],
        };

        // Return data for requested client or empty response if not found
        const response = mockData[clientCode] || emptyResponse;

        // If only past month requested, filter the data
        if (isOnlyPastMonth && response.primavera_orders.length > 0) {
            const oneMonthAgo = new Date();
            oneMonthAgo.setMonth(oneMonthAgo.getMonth() - 1);

            const filteredOrders = response.primavera_orders.filter(
                (order) =>
                    new Date(order.primavera_order_header.DataDoc) >=
                    oneMonthAgo
            );

            return {
                result: 'success',
                result_code: 200,
                total: filteredOrders.length,
                primavera_orders: filteredOrders,
            };
        }

        return response;
    }
}
