/* eslint-disable @typescript-eslint/naming-convention */

export interface PrimaveraClient {
    cliente: string;
    nome: string;
    contribuinte: string;
    morada: string;
    morada1?: string;
    localidade?: null;
    codPostal: string;
    codPostalLocalidade: string;
    pais: string;
    distrito?: string;
    telemovel: string;
    email?: string;
    condPag: string;
    modoPag: string;
    moeda: string;
    tipoPvp: number;
    desconto: number;
    clienteAnulado: boolean;
    avaliacao: string;
    codCesce?: string;
    plafoundCesce: string | null;
    emailCliente?: string;
    emailQualidade?: string;
    carro?: string;
}

export interface PrimaveraOrderLine {
    IdCabec: string;
    Id: string;
    TipoDoc: string;
    Serie: string;
    NumDoc: number;
    NumLinha: number;
    Artigo: null | string | string;
    Descricao: null | string | string;
    PrecUnit: number;
    Quantidade: number;
    PrecoLiquido: number;
    Moeda: string;
    Unidade: null | string | string;
    CodIva: null | string | string;
    TaxaIva: number;
    Armazem: null | string | string;
    Lote: string;
    Desconto1: number;
    Desconto2: number;
    Desconto3: number;
    DataLinha: string;
    DataEntrega: null | string | string;
    Vendedor: null | string | string;
    NomeVendedor: null | string | string;
    ComissaoVendedor: number;
    Observacoes: null;
    TipoOperacao: null;
    DescTipoOpercao: null;
    IvaRegraCalculo: string;
    CodigoPautal: null;
    MassaLiqLinha: number;
    ValorLiqLinha: number;
    IdObra: null;
}

export interface PrimaveraOrderHeader {
    Id: string;
    TipoDoc: string;
    Serie: string;
    NumDoc: number;
    TipoEntidade: string;
    Entidade: string;
    Nome: string;
    NumContribuiente: string;
    TotalDocumento: number;
    Moeda: string;
    Cambio: number;
    DataDoc: string;
    Estado: string;
    DescEstado: string;
    MoradaAltEntrega: null;
    Morada: string;
    Morada2: null;
    Localidade: string;
    CodPostal: string;
    CodPostalLocalidade: string;
    Distrito: string;
    Pais: string;
    DataCarga: null;
    Matricula: null;
    LocalCarga: string;
    MoradaCarga: string;
    Morada2Carga: null;
    LocalidadeCarga: string;
    CodPostalCarga: string;
    CodPostalLocalidadeCarga: string;
    DistritoCarga: null;
    PaisCarga: string;
    DataDescarga: null;
    LocalDescarga: string;
    MoradaDescarga: string;
    Morada2Descarga: null | string;
    LocalidadeDescarga: null | string;
    CodPostalDescarga: string;
    CodPostalLocalidadeDescarga: string;
    DistritoDescarga: null | string;
    PaisDescarga: null | string;
    EntidadeDescarga: string;
    TipoEntidadeDescarga: string;
    ObservacoesCabec: null | string;
    Referencia: string;
    DescontoEntidade: number;
    DescontoFinanceiro: number;
    ModoPagamento: string;
    CondicaoPagamento: string;
    DataVencimento: string;
    ModoExpedicao: null | string;
    TipoEntidadeFaturacao: string;
    EntidadeFaturacao: string;
    MoradaFaturacao: string;
    Morada2Faturacao: null;
    LocalidadeFaturacao: string;
    CodPostalFaturacao: string;
    LocalidadeCodPostalFaturacao: string;
    DistritoFaturacao: string;
    EspacoFiscal: string;
    RegimeIva: string;
    TipoOperacaoCabec: null;
    DescTipoOperacaoCabec: null;
    Documento: string;
    VendedorCabec: string;
    NomeVendedorCabec: string;
}
